const MODAL_REQUEST = "@modal/MODAL_REQUEST";
const MODAL_SUCCESS = "@modal/MODAL_SUCCESS";
const MODAL_FAILED = "@modal/MODAL_FAILED";
const MODAL_RESET = "@modal/MODAL_RESET";

export { MODAL_REQUEST, MODAL_SUCCESS, MODAL_FAILED, MODAL_RESET };