const JOB_DETAIL_REQUEST = '@jobDetail/JOB_DETAIL_REQUEST';
const JOB_DETAIL_SUCCESS = '@jobDetail/JOB_DETAIL_SUCCESS';
const JOB_DETAIL_FAILED = '@jobDetail/JOB_DETAIL_FAILED';

export { JOB_DETAIL_REQUEST, JOB_DETAIL_SUCCESS, JOB_DETAIL_FAILED }