const SUB_JOBS_REQUEST = '@subJobs/SUB_JOBS_REQUEST';
const SUB_JOBS_SUCCESS = '@subJobs/SUB_JOBS_SUCCESS';
const SUB_JOBS_FAILED = '@subJobs/SUB_JOBS_FAILED';

export { SUB_JOBS_REQUEST, SUB_JOBS_SUCCESS, SUB_JOBS_FAILED }